### ISSUE TITLE
师傅请问在哪个cs版本上可以使用哇

### ISSUE THREAD

**Issue by m0s30** [fdx-xdf/Rust_Beacon#1]

**Comment by fdx-xdf** [comment]
我是在4.5下面测试的，理论上4+版本都可以

**Comment by m0s30** [comment]
> 我是在4.5下面测试的，理论上4+版本都可以

支持哪些监听器呀

**Comment by fdx-xdf** [comment]
目前只实现了http，其他的有时间再加上去

**Comment by m0s30** [comment]
> 目前只实现了http，其他的有时间再加上去
师傅这个报错是什么原因
![image](https://github.com/user-attachments/assets/9986aa76-6c4f-45fb-8116-589d297393c5)

**Comment by fdx-xdf** [comment]
你没用自定义的profile吧

**Comment by m0s30** [comment]
> 你没用自定义的profile吧

两个都试过，用了和不用也是一样的

**Comment by fdx-xdf** [comment]
要不然你用ide调一下，看一下调用堆栈和调用参数，
看报错是说长度不合法，我这边没有这个问题

**Comment by m0s30** [comment]
> 要不然你用ide调一下，看一下调用堆栈和调用参数， 看报错是说长度不合法，我这边没有这个问题

是不能用自定义profile吗，有无详细配置readme呀

**Comment by fdx-xdf** [comment]
如果要用profile，需要自己改config.rs里面的东西
默认是和没有profile的Server端连接的

**Comment by m0s30** [comment]
> 如果要用profile，需要自己改config.rs里面的东西 默认是和没有profile的Server端连接的

师傅可以把监听器和C2_GET_URL、C2_POST_URL的值给我看看吗，这两个应该填什么呢

**Comment by fdx-xdf** [comment]
我这两个值就是项目里的，监听器的话我现在不太方便看

**Comment by m0s30** [comment]
> 我这两个值就是项目里的，监听器的话我现在不太方便看

可以了师傅，那两个值的uri不改就可以了

**Comment by fdx-xdf** [comment]
那两个值是cs默认的，如果要改的话结合profile一起改，后面我看看写个python脚本解析profile应该更好一点
