### ISSUE TITLE
为什么 要使用 nightly 版本？

### ISSUE THREAD

**Issue by badboycxcc** [fdx-xdf/Rust_Beacon#2]
```
  Compiling printf-compat v0.1.1
error[E0554]: #![feature] may not be used on the stable release channel
   --> /home/cx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/printf-compat-0.1.1/src/lib.rs:116:1
    |
116 | #![feature(c_variadic)]
    | ^^^^^^^^^^^^^^^^^^^^^^^

   Compiling sha2 v0.10.8
For more information about this error, try rustc --explain E0554.
error: could not compile printf-compat (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by fdx-xdf** [comment]
因为启用了一个不稳定特性，应该是bof加载功能用到的

**Comment by badboycxcc** [comment]
看代码，只适配度了Windows？

**Comment by fdx-xdf** [comment]
常规的文件 进程管理之类用的官方包，应该适配linux了，不过我自己没做测试😆

**Comment by badboycxcc** [comment]
怎么跨平台编译一堆错误？

**Comment by badboycxcc** [comment]
好吧，架构限制了x86_64，想编译arm 架构的就报错。

**Comment by badboycxcc** [comment]
上线执行 shell whoami 就直接退出了

<img width="643" alt="截屏2024-10-29 下午10 45 28" src="https://github.com/user-attachments/assets/40f52ef4-623b-481f-9b86-a47f0f852345">

**Comment by fdx-xdf** [comment]
上线信息显示正常吗
如果正确进入到shell里面会打印参数的

**Comment by badboycxcc** [comment]
正常上线的，没问题。
<img width="455" alt="截屏2024-10-30 上午7 53 42" src="https://github.com/user-attachments/assets/e127b03b-e06e-43a0-923c-d3bdf2d8d972">

**Comment by fdx-xdf** [comment]
你换成http的监听器试一下

**Comment by badboycxcc** [comment]
https 那边我增加了绕过 SSL 证书校验代码，我debug调试一下看看那个地方有问题。

**Comment by badboycxcc** [comment]
https 现在也没有问题了，很奇怪，难道是编译各环节问题？昨天实在kali arm 架构编译，今天是x86 架构编译的。
![image](https://github.com/user-attachments/assets/963dbfa2-3bf0-497a-b7cc-43441b049dac)
