### ISSUE TITLE
【BUG】 命令行下PS

### ISSUE THREAD

**Issue by badboycxcc** [fdx-xdf/Rust_Beacon#3]

**Comment by badboycxcc** [comment]
![image](https://github.com/user-attachments/assets/4d6a3dcf-3e15-4c47-965d-fb01cfd01542)

**Comment by badboycxcc** [comment]
终端打印的倒是信息完整，推测是上传那块有问题
![image](https://github.com/user-attachments/assets/a6b61f91-21b1-4250-9ff7-54039734cf66)

**Comment by fdx-xdf** [comment]
这个server端打印的没啥问题吧

**Comment by badboycxcc** [comment]
CS Server 终端打印的进程少了，只打印了一部分。

**Comment by badboycxcc** [comment]
我把很大打印的信息干掉后现在这个错误又不能复现了，奇怪，这个我先关了。
