### ISSUE TITLE
【问题】如果编译隐藏终端输出、隐藏终端输出？

### ISSUE THREAD

**Issue by badboycxcc** [fdx-xdf/Rust_Beacon#7]
实战中的话肯定是隐蔽运行的，不打印任何信息。

**Comment by fdx-xdf** [comment]
这个后续可以研究一下，把输出语句弄成条件编译

**Comment by badboycxcc** [comment]
实现了一个，但是还是有三个一闪而过的黑框
![PixPin_2024-10-30_12-49-00](https://github.com/user-attachments/assets/7b17bed6-9e8b-47d4-8e6a-2cdfa0b82f79)

**Comment by badboycxcc** [comment]
用的是这个方法

```
#![windows_subsystem = "windows"]
```

**Comment by badboycxcc** [comment]
已实现。
https://github.com/user-attachments/assets/b435080a-27ea-45c1-a652-f1b3eedfb7e2
